"""PDF invoice generation using fpdf2 -- Brutalist Command palette."""

from pathlib import Path

from fpdf import FPDF

from invoicegen.models import Invoice


# Brutalist Command palette as RGB tuples
_SURFACE = (14, 14, 14)
_SURFACE_HIGH = (30, 30, 30)
_PRIMARY_RGB = (159, 255, 136)   # #9fff88
_SECONDARY_RGB = (0, 251, 251)   # #00fbfb
_TERTIARY_RGB = (68, 165, 255)   # #44a5ff
_ERROR_RGB = (255, 85, 85)       # #ff5555
_TEXT_LIGHT = (220, 220, 220)
_TEXT_DIM = (140, 140, 140)
_WHITE = (255, 255, 255)


class InvoicePDF(FPDF):
    """Custom PDF class with Brutalist Command dark-theme layout."""

    def __init__(self, invoice: Invoice):
        super().__init__()
        self.invoice = invoice
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        # Dark header bar
        self.set_fill_color(*_SURFACE)
        self.rect(0, 0, 210, 40, "F")

        # INVOICE title in primary green
        self.set_font("Helvetica", "B", 24)
        self.set_text_color(*_PRIMARY_RGB)
        self.set_xy(15, 10)
        self.cell(0, 10, "INVOICE", ln=False)

        # Invoice metadata in secondary cyan
        self.set_font("Helvetica", "", 11)
        self.set_text_color(*_SECONDARY_RGB)
        self.set_xy(140, 10)
        self.cell(0, 6, self.invoice.invoice_number, ln=True, align="R")
        self.set_text_color(*_TEXT_DIM)
        self.set_xy(140, 17)
        self.cell(0, 6, f"Date: {self.invoice.created_at}", ln=True, align="R")
        self.set_xy(140, 24)
        self.cell(0, 6, f"Due: {self.invoice.due_date}", ln=True, align="R")

        self.ln(25)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*_TEXT_DIM)
        self.cell(
            0, 10,
            f"Generated by InvoiceGen | Page {self.page_no()}",
            align="C",
        )


def generate_pdf(invoice: Invoice, output_path: str | None = None) -> Path:
    """Generate a professional PDF invoice with Brutalist Command styling.

    Args:
        invoice: The invoice data to render.
        output_path: Optional output file path. Defaults to current directory.

    Returns:
        Path to the generated PDF file.
    """
    if output_path is None:
        output_path = f"{invoice.invoice_number}.pdf"

    pdf = InvoicePDF(invoice)
    pdf.add_page()

    # Bill To section
    pdf.set_y(50)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*_SECONDARY_RGB)
    pdf.cell(0, 7, "BILL TO", ln=True)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, invoice.client_name, ln=True)
    if invoice.client_email:
        pdf.cell(0, 6, invoice.client_email, ln=True)
    if invoice.client_address:
        for line in invoice.client_address.split(", "):
            pdf.cell(0, 6, line.strip(), ln=True)

    # Status badge with Brutalist colors
    pdf.set_xy(140, 50)
    status = invoice.effective_status
    badge_colors = {
        "Paid": _PRIMARY_RGB,
        "Overdue": _ERROR_RGB,
        "Sent": _TERTIARY_RGB,
        "Draft": _TEXT_DIM,
    }
    pdf.set_fill_color(*badge_colors.get(status, _TEXT_DIM))

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*_SURFACE)
    status_width = pdf.get_string_width(status) + 16
    pdf.cell(status_width, 10, status, fill=True, align="C")

    # Line items table
    pdf.set_y(pdf.get_y() + 15 if pdf.get_y() > 85 else 95)

    # Table header -- dark surface with secondary cyan text
    pdf.set_fill_color(*_SURFACE)
    pdf.set_text_color(*_SECONDARY_RGB)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(120, 9, "  Description", fill=True)
    pdf.cell(60, 9, "Amount", fill=True, align="R")
    pdf.ln()

    # Table rows -- alternating subtle stripes
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    fill = False
    for item in invoice.items:
        if fill:
            pdf.set_fill_color(245, 245, 245)
        else:
            pdf.set_fill_color(255, 255, 255)
        pdf.cell(120, 8, f"  {item.description}", fill=True)
        pdf.cell(60, 8, f"${item.amount:,.2f}", fill=True, align="R")
        pdf.ln()
        fill = not fill

    # Totals section
    pdf.ln(3)
    totals_x = 120
    pdf.set_x(totals_x)

    # Divider line in secondary cyan
    pdf.set_draw_color(*_SECONDARY_RGB)
    pdf.line(totals_x, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3)

    # Subtotal
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.set_x(totals_x)
    pdf.cell(40, 7, "Subtotal:", align="R")
    pdf.cell(35, 7, f"${invoice.subtotal:,.2f}", align="R")
    pdf.ln()

    # Tax
    if invoice.tax_rate > 0:
        pdf.set_x(totals_x)
        pdf.cell(40, 7, f"Tax ({invoice.tax_rate}%):", align="R")
        pdf.cell(35, 7, f"${invoice.tax_amount:,.2f}", align="R")
        pdf.ln()

    # Total row -- dark bar with primary green text
    pdf.ln(1)
    pdf.set_fill_color(*_SURFACE)
    pdf.set_text_color(*_PRIMARY_RGB)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_x(totals_x)
    pdf.cell(40, 10, "TOTAL:", fill=True, align="R")
    pdf.cell(35, 10, f"${invoice.total:,.2f}", fill=True, align="R")
    pdf.ln()

    # Notes
    if invoice.notes:
        pdf.ln(15)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*_SECONDARY_RGB)
        pdf.cell(0, 7, "Notes:", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_TEXT_DIM)
        pdf.multi_cell(0, 5, invoice.notes)

    # Payment terms footer
    pdf.ln(10)
    pdf.set_draw_color(*_TEXT_DIM)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(5)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(*_TEXT_DIM)
    pdf.cell(
        0, 5,
        f"Payment due within {_days_until_due(invoice)} days of invoice date.",
        ln=True, align="C",
    )
    pdf.cell(0, 5, "Thank you for your business!", ln=True, align="C")

    out = Path(output_path)
    pdf.output(str(out))
    return out


def _days_until_due(invoice: Invoice) -> int:
    """Calculate net days from created_at to due_date."""
    from datetime import datetime

    try:
        created = datetime.strptime(invoice.created_at, "%Y-%m-%d").date()
        due = datetime.strptime(invoice.due_date, "%Y-%m-%d").date()
        return (due - created).days
    except (ValueError, TypeError):
        return 30
